### ISSUE TITLE
Feature: Change might and vuln generation from binary to expected stacks

### ISSUE THREAD

**Issue by DioVento** [RaidcoreGG/GW2-CommandersToolkit#20] opened 2022-09-19 01:32 UTC
Would pair really well with having templates for DPS classes that generate incidental Might and Vuln, especially since there are support combos that don't guarantee 25 Might like CSpecter+CQB.

**Comment by DeltaRaidcore** [comment] 2022-09-19 14:05
Duplicate of #13

**Closed as completed by DeltaRaidcore** 2022-09-19 14:05 UTC
